version: '3'
services:
  frontend: 
    build: ./front 
    ports: #
      - "3000:3000" 
    container_name: frontend-docker
    restart: always 
    links:
      - backend
 
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    container_name: backend-docker
    restart: always
 
